version: '3.8'

services:
  app:
    build: .
    environment:
      - PORT=3000
      - SECRET_MESSAGE=${SECRET_MESSAGE} # Use Vault secret here
    ports:
      - "3000:3000"
    depends_on:
      - vault

  vault:
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: hvs.wuS9u8UxsGuc6varpKbeupYf
      VAULT_ADDR: http://vaultstest.sociumtech.com
