name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Hetzner
        run: echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl docker.io

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/id_rsa root@HETZNER_IP \
          'cd /root/Vault && git pull && ./fetch-secrets.sh'
