name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1


      - name: Login to Hetzner Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y jq curl docker.io
            cd /root/Vault
            git pull
            chmod +x fetch-secrets.sh
            ./fetch-secrets.sh
