name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker image
      run: |
          docker build -t ${{ secrets.DOCKER_USER }}/node-docker-vault-hetzner:latest .
          docker push ${{ secrets.DOCKER_USER }}/node-docker-vault-hetzner:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hetzner server
        uses: appleboy/ssh-action@v1.0.0
        with:
           host: ${{ secrets.HETZNER_IP }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_KEY }}
           

           script: |  
               docker pull ${{ secrets.DOCKER_USER }}/node-docker-vault-hetzner:latest &&
               docker stop node-docker-vault-hetznerC || true &&
               docker rm node-docker-vault-hetznerC || true &&
               docker run -d --name node-docker-vault-hetznerC -p 3000:3000 ${{ secrets.DOCKER_USER }}/node-docker-vault-hetzner:latest

    
        env:
           VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
           VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
