name: Node.js CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Fetch secrets from Vault
        env:
          VAULT_ADDR: "http://vault.sociumtech.com"
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          vault kv get -field=DB_PASSWORD secret/myapp > .env
      - name: Run the app
        run: node index.js
